Kbuild: Fix -Wframe-larger-than
Move the -Wframe-larger-than flag setting outside the $(call cc-option-yn,
-Wmaybe-uninitialized) check because this check is in no way related to
our flag, and moreover, when using the Clang compiler, the flag setting
will never be reached since Clang knows nothing about -Wmaybe-uninitialized
only -Wuninitialized is familiar to it.

Fixes:
drivers/staging/wlan-qc/qcacld-3.0/../qca-wifi-host-cmn/dp/wifi3.0/dp_ipa.c:1289:12:
error: stack frame size (2544) exceeds limit (2048) in 'dp_ipa_setup' [-Werror,-Wframe-larger-than]
QDF_STATUS dp_ipa_setup(struct cdp_soc_t *soc_hdl, uint8_t pdev_id,
           ^
1 error generated.

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>